export enum AuditEvents {
    USER_CREATE = 2 ** 0,
    USER_UPDATE = 2 ** 1,
    USER_DELETE = 2 ** 2,
    USER_ROLE_UPDATE = 2 ** 3,

    SUBMISSION_CREATE = 2 ** 4,
    SUBMISSION_UPDATE = 2 ** 5,
    SUBMISSION_DELETE = 2 ** 6,
    SUBMISSION_BULK_DELETE = 2 ** 7,
    SUBMISSION_ENJOYMENT_DELETE = 2 ** 8,
    SUBMISSION_MERGE = 2 ** 9,

    PENDING_SUBMISSION_UPDATE = 2 ** 10,
    PENDING_SUBMISSION_DELETE = 2 ** 11,
    PENDING_SUBMISSION_DELETE_ALL = 2 ** 12,

    TAG_CREATE = 2 ** 14,
    TAG_UPDATE = 2 ** 14,
    TAG_DELETE = 2 ** 15,
    TAG_VOTES_DELETE = 2 ** 16,

    PASSWORD_RESET_LINK_CREATE = 2 ** 17,

    ROLE_CREATE = 2 ** 18,
    ROLE_UPDATE = 2 ** 19,
    ROLE_DELETE = 2 ** 20,

    PLATFORMER_LIST_LEVEL_CREATE = 2 ** 21,
    PLATFORMER_LIST_LEVEL_UPDATE = 2 ** 22,
    PLATFORMER_LIST_LEVEL_DELETE = 2 ** 23,

    PACK_CREATE = 2 ** 24,
    PACK_UPDATE = 2 ** 25,
    PACK_DELETE = 2 ** 26,

    PACK_LEVEL_CREATE = 2 ** 27,
    PACK_LEVEL_DELETE = 2 ** 28,

    USER_BAN_CREATE = 2 ** 29,
    USER_BAN_REVOKE = 2 ** 30,
}
